### ISSUE TITLE
SyumiruSelectionModule.py内のLine通知関数について

### ISSUE THREAD

**Issue by our-holyland** [Syumiru/Poke-Controller-Modified-PGM#10]
SyumiruSelectionModule.py内にてLINE_image()が使われておりますが、
Modified版でもExtension版でも第二引数にTrueはふさわしくないと思われます。
(LINE_image()がCallされてもLINE_image()内に
 例外処理があるため、プログラムが終了しませんでした。)

<img width="1040" alt="スクリーンショット 2024-09-10 23 49 27" src="https://github.com/user-attachments/assets/a0ec5fb0-f117-4aa5-8fe7-b2dd6898af23">

SyumiruSelectionModule.pyの設計思想上、
本家Poke-ControllerでもLINE通知ができるよう
LINE_image‎()ではなく、LINE_Message()を使うべきかと愚考しますが
確認をお願いできますでしょうか？

**Comment by Syumiru** [comment]
ご指摘ありがとうございます。

Pythonを触るのはポケコンスクリプトが初めての初心者ということをご承知おきください。
プログラミング初心者ではないのでなんとなく動くものを作っている感じです。

> SyumiruSelectionModule.py内にてLINE_image()が使われておりますが、 Modified版でもExtension版でも第二引数にTrueはふさわしくないと思われます。

改めて確認すると引数定義されているにも関わらず不一致の型で引数渡しが行われているようなので（とりあえず動作していることに驚きました）、
ふさわしいかと言われればふさわしくないと私も思いますが、
どこまで許容されるのか知りたい、試してみたいという好奇心もあり修正する必要性を感じていません。
> (LINE_image()がCallされてもLINE_image()内に 例外処理があるため、プログラムが終了しませんでした。) 

LINE_image()をExtension版v0.0.5で確認しましたが、該当する例外処理を確認できませんでした。
私がPGM実行していて例外パターンに入っていることを確認できたこともありませんでした。

> SyumiruSelectionModule.pyの設計思想上、 本家Poke-ControllerでもLINE通知ができるよう LINE_image‎()ではなく、LINE_Message()を使うべきかと愚考しますが 確認をお願いできますでしょうか？

SyumiruSelectionModule.pyの設計思想は2点です。
1. 自分が使用した実績のあり、汎用性のある（ソフトリセットやLINE通知など）モジュールの共通化
2. ini関連処理の共通化

したがって、本家Poke-Controllerで使えるようにするという設計思想はそもそもないです。
また、あまり使っているという人をお見かけしたことがないため、対応する予定もないです。

以上、回答になっていれば幸いです。

**Comment by our-holyland** [comment]
ご回答ありがとうございます。

> ふさわしいかと言われればふさわしくないと私も思いますが、
> どこまで許容されるのか知りたい、試してみたいという好奇心もあり修正する必要性を感じていません。

自分もプログラムは好奇心で書いてるので気持ちは大変わかります。
プログラムも異常終了はしませんし、Syumiru様が修正不要と判断するなら
それも一つの結論だと思います。

>>(LINE_image()がCallされてもLINE_image()内に 例外処理があるため、プログラムが終了しませんでした。)

> LINE_image()をExtension版v0.0.5で確認しましたが、該当する例外処理を確認できませんでした。
> 私がPGM実行していて例外パターンに入っていることを確認できたこともありませんでした。

自分の理解不足と説明不足があり、申し訳ございません。
自分が本事象を確認したのはModified版v3.0.2.7.0です。

LINE_image()内でコールされるsend_text_n_image()にて異常が発生し、
下記該当ログを出力してLINE_image()内の例外処理(except)に遷移し、
プログラムは終了しませんでしたが、LINE通知は行われませんでした。
(Extension版はそこまで動かしてないので、自分がコードを拝見する限りですが、
 Extension版のLINE_image()は、例外処理に遷移しませんし、
 LINE通知は行いそうですね)

・該当ログ
　2024-09-11 21:33:16,887 LineNotify send_text_n_image [ERROR]: Using the wrong token

> したがって、本家Poke-Controllerで使えるようにするという設計思想はそもそもないです。

了解です。設計思想のご教授ありがとうございます。
本プログラムを自分の環境で動かすためのチューニングだったり、なんだったりの目的で
いじったり、なんだったりしてるので大変勉強になります。

> また、あまり使っているという人をお見かけしたことがないため、対応する予定もないです。

A0S0赫月ガチグマやC0パオジアンなんてみんな欲しいはずなのに。。。
個人的に本プログラムがあまり使われていないというのが一番のバグだと思ってます(笑)

色々とご回答ありがとうございました。
Syumiru様の方で問題がなければ、自分が投稿した別のisuueも含めて
お手数おかけしますがclose願います。

最後に、素晴らしい本プログラムを開発、公開して頂いたSyumiru様に
この場をお借りして心から感謝申し上げます。

**Comment by Syumiru** [comment]
> 自分の理解不足と説明不足があり、申し訳ございません。 自分が本事象を確認したのはModified版v3.0.2.7.0です。
> 
> LINE_image()内でコールされるsend_text_n_image()にて異常が発生し、 下記該当ログを出力してLINE_image()内の例外処理(except)に遷移し、 プログラムは終了しませんでしたが、LINE通知は行われませんでした。 (Extension版はそこまで動かしてないので、自分がコードを拝見する限りですが、 Extension版のLINE_image()は、例外処理に遷移しませんし、 LINE通知は行いそうですね)
なるほど、専らExtension版ばかり使用しているので分からなかったのかもしれません。
対応した方が良いことは分かるのですが、Extension版に移行している人も多そうなので、対応予定はありません。

> > また、あまり使っているという人をお見かけしたことがないため、対応する予定もないです。
> 
> A0S0赫月ガチグマやC0パオジアンなんてみんな欲しいはずなのに。。。 個人的に本プログラムがあまり使われていないというのが一番のバグだと思ってます(笑)
嬉しいお言葉ありがとうございます。

補足ですが、ここでいう使っているという人を見かけないというのは、
本家Poke-controllerのことで、本PGMのことではないです笑
わざわざ使用者の少なそうなPoke-controllerの仕様に合わせた改修はしないという意味でした。

また、何かあればご連絡ください。
ご返答ありがとうございました。
