### ISSUE TITLE
C0パオジアン厳選PGMにおけるアメタマの努力値について

### ISSUE THREAD

**Issue by our-holyland** [Syumiru/Poke-Controller-Modified-PGM#9]
READMEにてアメタマは努力値はなしとありますが、
ワナch様の動画を拝見する限り、
努力値を振らないと正しくC0判定は行われないはずです。

https://www.youtube.com/watch?v=drb6n50ORFA

つたないながらも自分の算出結果も添付させていただきますので、
お手数おかけしますが確認お願い致します。

<img width="1005" alt="スクリーンショット 2024-09-10 23 35 42" src="https://github.com/user-attachments/assets/7710e191-e8cb-4065-ba5a-324acdbd03cc">

**Comment by Syumiru** [comment]
ご指摘ありがとうございます。

私の理解不足でした。
私が努力値を振らないでC0パオジアン厳選が完了してしまったようで、気づいていませんでした。
README修正バージョンをリリースさせていただきます。

**Comment by Syumiru** [comment]
備忘のため補足
例:C0無補正パオジアン捕獲
6V無補正アメタマ(努力値なし)を使用すると、C14パオジアン（実数値:121）まで厳選完了判定となってしまう。

パワスワの式:(相手のとくこう+自分のとくこう)/2
※小数点以下切り捨て
自分のとくこうが想定より低いと、相手のとくこうが高くてもテラバーストが物理扱いになり、厳選完了判定となる。
